// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by: scripts/generate-lock-combinations.ts
// 
// This file contains all valid lock combinations.
// Locks used: 2, 4, 6, 8, 10
// Total combinations: 31

import { type LockContext as IronGuardLockContext } from '@markdrei/ironguard-typescript-locks';

// ===== INDIVIDUAL LOCK TYPES =====

/** Context holding ONLY lock 2 */
export type Only2 = IronGuardLockContext<readonly [2]>;

/** Context holding ONLY lock 4 */
export type Only4 = IronGuardLockContext<readonly [4]>;

/** Context holding ONLY lock 6 */
export type Only6 = IronGuardLockContext<readonly [6]>;

/** Context holding ONLY lock 8 */
export type Only8 = IronGuardLockContext<readonly [8]>;

/** Context holding ONLY lock 10 */
export type Only10 = IronGuardLockContext<readonly [10]>;

// ===== ALL COMBINATIONS =====

/** Context holding locks: [2] */
export type Locks2 = IronGuardLockContext<readonly [2]>;

/** Context holding locks: [4] */
export type Locks4 = IronGuardLockContext<readonly [4]>;

/** Context holding locks: [2, 4] */
export type Locks2_4 = IronGuardLockContext<readonly [2, 4]>;

/** Context holding locks: [6] */
export type Locks6 = IronGuardLockContext<readonly [6]>;

/** Context holding locks: [2, 6] */
export type Locks2_6 = IronGuardLockContext<readonly [2, 6]>;

/** Context holding locks: [4, 6] */
export type Locks4_6 = IronGuardLockContext<readonly [4, 6]>;

/** Context holding locks: [2, 4, 6] */
export type Locks2_4_6 = IronGuardLockContext<readonly [2, 4, 6]>;

/** Context holding locks: [8] */
export type Locks8 = IronGuardLockContext<readonly [8]>;

/** Context holding locks: [2, 8] */
export type Locks2_8 = IronGuardLockContext<readonly [2, 8]>;

/** Context holding locks: [4, 8] */
export type Locks4_8 = IronGuardLockContext<readonly [4, 8]>;

/** Context holding locks: [2, 4, 8] */
export type Locks2_4_8 = IronGuardLockContext<readonly [2, 4, 8]>;

/** Context holding locks: [6, 8] */
export type Locks6_8 = IronGuardLockContext<readonly [6, 8]>;

/** Context holding locks: [2, 6, 8] */
export type Locks2_6_8 = IronGuardLockContext<readonly [2, 6, 8]>;

/** Context holding locks: [4, 6, 8] */
export type Locks4_6_8 = IronGuardLockContext<readonly [4, 6, 8]>;

/** Context holding locks: [2, 4, 6, 8] */
export type Locks2_4_6_8 = IronGuardLockContext<readonly [2, 4, 6, 8]>;

/** Context holding locks: [10] */
export type Locks10 = IronGuardLockContext<readonly [10]>;

/** Context holding locks: [2, 10] */
export type Locks2_10 = IronGuardLockContext<readonly [2, 10]>;

/** Context holding locks: [4, 10] */
export type Locks4_10 = IronGuardLockContext<readonly [4, 10]>;

/** Context holding locks: [2, 4, 10] */
export type Locks2_4_10 = IronGuardLockContext<readonly [2, 4, 10]>;

/** Context holding locks: [6, 10] */
export type Locks6_10 = IronGuardLockContext<readonly [6, 10]>;

/** Context holding locks: [2, 6, 10] */
export type Locks2_6_10 = IronGuardLockContext<readonly [2, 6, 10]>;

/** Context holding locks: [4, 6, 10] */
export type Locks4_6_10 = IronGuardLockContext<readonly [4, 6, 10]>;

/** Context holding locks: [2, 4, 6, 10] */
export type Locks2_4_6_10 = IronGuardLockContext<readonly [2, 4, 6, 10]>;

/** Context holding locks: [8, 10] */
export type Locks8_10 = IronGuardLockContext<readonly [8, 10]>;

/** Context holding locks: [2, 8, 10] */
export type Locks2_8_10 = IronGuardLockContext<readonly [2, 8, 10]>;

/** Context holding locks: [4, 8, 10] */
export type Locks4_8_10 = IronGuardLockContext<readonly [4, 8, 10]>;

/** Context holding locks: [2, 4, 8, 10] */
export type Locks2_4_8_10 = IronGuardLockContext<readonly [2, 4, 8, 10]>;

/** Context holding locks: [6, 8, 10] */
export type Locks6_8_10 = IronGuardLockContext<readonly [6, 8, 10]>;

/** Context holding locks: [2, 6, 8, 10] */
export type Locks2_6_8_10 = IronGuardLockContext<readonly [2, 6, 8, 10]>;

/** Context holding locks: [4, 6, 8, 10] */
export type Locks4_6_8_10 = IronGuardLockContext<readonly [4, 6, 8, 10]>;

/** Context holding locks: [2, 4, 6, 8, 10] */
export type Locks2_4_6_8_10 = IronGuardLockContext<readonly [2, 4, 6, 8, 10]>;

// ===== UNION OF ALL VALID COMBINATIONS =====

/**
 * Union of all 31 valid lock combinations.
 * Use this when you want to accept any valid combination of locks.
 */
export type AnyValidLockCombination =
  Locks2
  | Locks4
  | Locks2_4
  | Locks6
  | Locks2_6
  | Locks4_6
  | Locks2_4_6
  | Locks8
  | Locks2_8
  | Locks4_8
  | Locks2_4_8
  | Locks6_8
  | Locks2_6_8
  | Locks4_6_8
  | Locks2_4_6_8
  | Locks10
  | Locks2_10
  | Locks4_10
  | Locks2_4_10
  | Locks6_10
  | Locks2_6_10
  | Locks4_6_10
  | Locks2_4_6_10
  | Locks8_10
  | Locks2_8_10
  | Locks4_8_10
  | Locks2_4_8_10
  | Locks6_8_10
  | Locks2_6_8_10
  | Locks4_6_8_10
  | Locks2_4_6_8_10;

// ===== LOCK-SPECIFIC GROUPINGS =====

/** Contexts that include lock 2 */
export type With2 =
  Locks2
  | Locks2_4
  | Locks2_6
  | Locks2_4_6
  | Locks2_8
  | Locks2_4_8
  | Locks2_6_8
  | Locks2_4_6_8
  | Locks2_10
  | Locks2_4_10
  | Locks2_6_10
  | Locks2_4_6_10
  | Locks2_8_10
  | Locks2_4_8_10
  | Locks2_6_8_10
  | Locks2_4_6_8_10;

/** Contexts that include lock 4 */
export type With4 =
  Locks4
  | Locks2_4
  | Locks4_6
  | Locks2_4_6
  | Locks4_8
  | Locks2_4_8
  | Locks4_6_8
  | Locks2_4_6_8
  | Locks4_10
  | Locks2_4_10
  | Locks4_6_10
  | Locks2_4_6_10
  | Locks4_8_10
  | Locks2_4_8_10
  | Locks4_6_8_10
  | Locks2_4_6_8_10;

/** Contexts that include lock 6 */
export type With6 =
  Locks6
  | Locks2_6
  | Locks4_6
  | Locks2_4_6
  | Locks6_8
  | Locks2_6_8
  | Locks4_6_8
  | Locks2_4_6_8
  | Locks6_10
  | Locks2_6_10
  | Locks4_6_10
  | Locks2_4_6_10
  | Locks6_8_10
  | Locks2_6_8_10
  | Locks4_6_8_10
  | Locks2_4_6_8_10;

/** Contexts that include lock 8 */
export type With8 =
  Locks8
  | Locks2_8
  | Locks4_8
  | Locks2_4_8
  | Locks6_8
  | Locks2_6_8
  | Locks4_6_8
  | Locks2_4_6_8
  | Locks8_10
  | Locks2_8_10
  | Locks4_8_10
  | Locks2_4_8_10
  | Locks6_8_10
  | Locks2_6_8_10
  | Locks4_6_8_10
  | Locks2_4_6_8_10;

/** Contexts that include lock 10 */
export type With10 =
  Locks10
  | Locks2_10
  | Locks4_10
  | Locks2_4_10
  | Locks6_10
  | Locks2_6_10
  | Locks4_6_10
  | Locks2_4_6_10
  | Locks8_10
  | Locks2_8_10
  | Locks4_8_10
  | Locks2_4_8_10
  | Locks6_8_10
  | Locks2_6_8_10
  | Locks4_6_8_10
  | Locks2_4_6_8_10;

// ===== STATISTICS =====
// Total lock combinations: 31
// - Single locks: 5
// - Pairs: 10
// - Triples: 10
// - Quadruples: 5
// - All five: 1
